### ISSUE TITLE
网站没有 favicon

### ISSUE THREAD

**Issue by CyrusYip** [Shitao5/shitao-blog#1]
加一个 favicon 会更有辨识度。如图：

<img width="117" alt="image" src="https://user-images.githubusercontent.com/60951091/186328975-91a042ca-de0f-42d1-a0c4-7bc9f5aff5dc.png">

你可以参考这个 commit https://github.com/CyrusYip/cyrusyip-blog/commit/cdc31158e04faaeb74cce8bebcae267c87c68c93 。

**Comment by Shitao5** [comment]
再次感谢叶寻（第n+1次感谢），这个favicon暂时没想好，我想到有点多，想要符合自身形象，又能传达出自己的态度，有点难为自己的艺术细胞了。上次看到制作favicon的网站<https://www.sp-studio.de/>，好像也是yihui分享的。我再次把加favicon的事情提上日程，而不是在todo里边石沉大海了……

**Comment by CyrusYip** [comment]
我一开始以为你忘记弄 favicon 了，后来才在代办列表看到。我之前问益辉从哪里弄的头像，他就说那个网站，于是我也在那里弄了个头像。

**Comment by Shitao5** [comment]
@CyrusYip 已添加，谢谢！
