### ISSUE TITLE
暗色模式下 emoji 的颜色不正常

### ISSUE THREAD

**Issue by CyrusYip** [Shitao5/shitao-blog#51]
![Screenshot_20240724_175312](https://github.com/user-attachments/assets/aed176ca-e459-4e39-8d45-f677545972d5)

已反馈到上游：<https://github.com/yihui/hugo-paged/issues/7>。

**Comment by yihui** [comment]
如果是我，就会直接去掉这两个字符。颜文字带来的技术麻烦都非常麻烦。

**Comment by Shitao5** [comment]
@CyrusYip 感谢叶寻。我手机上一直是暗色模式，这个「不正常」还可以接受的。 

@yihui 哈哈益辉的想法在意料之中。颜文字不在主题设计的考虑范围，使用者「自由选择，承担责任」😀

**Comment by yihui** [comment]
世上无难事，只要肯放弃！
